-- | The verifier-side inputs of an OCaml-produced wrap proof, for the Lean kimchi
-- | verifier's recursion fixture (`tools/fixture-dump`'s `kimchi_proof_dump_pickles`,
-- | `formal/kimchi/fixtures/kimchi_proof_pallas_pickles.json`).
-- |
-- | The side-loaded fixture directories carry the kimchi proof and key as the Rust
-- | prover made them (`proof.serde.json`, `vk.serde.json`) but not what the terminator
-- | computes to verify them: the wrap public input (the expanded deferred values and the
-- | two recomputed message digests, `wrapPublicInputVP`) and the accumulator list it
-- | opens the proof at (`wrapAccumulators`). This spec writes both to
-- | `lean_inputs.json` beside the proof when the file is absent, and otherwise asserts
-- | the committed file is what the verifier computes today — so the Lean fixture is
-- | regenerated by deleting the file and re-running. Field elements are decimal
-- | strings, the Lean fixtures' encoding.
-- |
-- | `simple_chain/wrap1` is the second proof of a plain self-recursive chain: its
-- | accumulator list is one dummy and the real accumulator of `wrap0`. The wrap domain
-- | is 2^14 below the 2^15 Tock SRS — production's sub-SRS `chunk_size = 1` regime, one
-- | chunk to the Lean verifier.
module Test.Pickles.Sideload.LeanInputsSpec (spec) where

import Prelude

import Colog (LoggerT, Message)
import Data.Array as Array
import Data.Either (either)
import Effect.Aff (Aff)
import Effect.Aff.Class (liftAff)
import Effect.Class (liftEffect)
import Effect.Exception (throw)
import JS.BigInt as BigInt
import Node.Encoding (Encoding(..))
import Node.FS.Sync (exists, readTextFile, writeTextFile)
import Pickles.Verify (verifyStages, wrapAccumulators, wrapPublicInputVP)
import Simple.JSON (readJSON, writeJSON)
import Snarky.Curves.Class (class PrimeField, toBigInt)
import Test.Pickles.SharedSrs (SharedSrs)
import Test.Pickles.Sideload.Loader (decodeHex, loadFixture)
import Test.Spec (SpecT, describe, it)
import Test.Spec.Assertions (shouldEqual)

-- | The file's shape: every field element a decimal string.
type LeanInputs =
  { publicInput :: Array String
  , prevChallenges :: Array { sgX :: String, sgY :: String, challenges :: Array String }
  }

spec :: SpecT (LoggerT Message Aff) SharedSrs Aff Unit
spec = describe "Pickles.Sideload.LeanInputs" do
  it "simple_chain b1 (mpv=1): the wrap public input and accumulator list, for Lean"
    (liftAff <<< body "packages/pickles/test/fixtures/simple_chain/wrap1")
  where
  body :: String -> SharedSrs -> Aff Unit
  body dir { pallasSrs, vestaSrs } = do
    fixture <- loadFixture { decodeStatement: decodeHex, statementToFields: \f -> [ f ] } { pallasSrs, vestaSrs } dir
    -- The inputs are only meaningful for a proof the terminator accepts.
    verifyStages fixture.verifier fixture.verifiableProof
      `shouldEqual` { accumulatorOk: true, kimchiOk: true }
    let
      dec :: forall f. PrimeField f => f -> String
      dec = BigInt.toString <<< toBigInt

      computed :: LeanInputs
      computed =
        { publicInput: map dec (wrapPublicInputVP fixture.verifier fixture.verifiableProof)
        , prevChallenges:
            map (\a -> { sgX: dec a.sgX, sgY: dec a.sgY, challenges: map dec a.challenges })
              (wrapAccumulators fixture.verifier fixture.verifiableProof)
        }
      path = dir <> "/lean_inputs.json"
    present <- liftEffect $ exists path
    if present then do
      text <- liftEffect $ readTextFile UTF8 path
      committed :: LeanInputs <- either (liftEffect <<< throw <<< show) pure (readJSON text)
      committed `shouldEqual` computed
    else do
      liftEffect $ writeTextFile UTF8 path (writeJSON computed)
      Array.length computed.prevChallenges `shouldEqual` 2
