import Pickles.Linearization.Types

/-!
# Emitting a token stream as Lean source

The counterpart of `pickles-codegen`'s `Generator.purs`, which turns the same JSON dump
into `Pickles.Linearization.{Pallas,Vesta}`. A statement about the deployed linearization
needs the stream as a CLOSED TERM — `readLinearization` hands back an `IO` value, which no
theorem can mention — so the generated module is what a reflection proof would quantify
over.

Generated modules are build artifacts, gitignored exactly as `Pallas.purs`/`Vesta.purs`
are, and produced by `make gen-linearization`.
-/

namespace Pickles.Fixture

open Pickles.Linearization

/-! ## Rendering -/

/-- An `Int` as a Lean literal, parenthesised when negative so it parses in argument
position. -/
private def intLit (i : Int) : String := if i < 0 then s!"({i})" else toString i

/-- A row selector. -/
private def rowSrc : CurrOrNext → String
  | .curr => ".curr"
  | .next => ".next"

/-- A gate name. -/
private def gateSrc : GateType → String
  | .generic => ".generic"          | .poseidon => ".poseidon"
  | .completeAdd => ".completeAdd"  | .varBaseMul => ".varBaseMul"
  | .endoMul => ".endoMul"          | .endoMulScalar => ".endoMulScalar"
  | .rangeCheck0 => ".rangeCheck0"  | .rangeCheck1 => ".rangeCheck1"
  | .foreignFieldAdd => ".foreignFieldAdd"
  | .foreignFieldMul => ".foreignFieldMul"
  | .xor16 => ".xor16"              | .rot64 => ".rot64"

/-- A lookup family. -/
private def lpSrc : LookupPattern → String
  | .lookup => ".lookup"          | .xor => ".xor"
  | .rangeCheck => ".rangeCheck"  | .foreignFieldMul => ".foreignFieldMul"

/-- A column reference. -/
private def colSrc : Column → String
  | .witness i => s!"(.witness {i})"
  | .coefficient i => s!"(.coefficient {i})"
  | .index g => s!"(.index {gateSrc g})"
  | .lookupSorted i => s!"(.lookupSorted {i})"
  | .lookupAggreg => ".lookupAggreg"
  | .lookupTable => ".lookupTable"
  | .lookupRuntimeTable => ".lookupRuntimeTable"
  | .lookupRuntimeSelector => ".lookupRuntimeSelector"
  | .lookupKindIndex p => s!"(.lookupKindIndex {lpSrc p})"

/-- A constant. -/
private def constSrc : ConstantTerm → String
  | .endoCoefficient => ".endoCoefficient"
  | .mds r c => s!"(.mds {r} {c})"
  | .literal v => s!"(.literal {v})"

/-- A challenge. -/
private def chalSrc : ChallengeTerm → String
  | .alpha => ".alpha"  | .beta => ".beta"
  | .gamma => ".gamma"  | .jointCombiner => ".jointCombiner"

/-- A feature predicate. -/
private def flagSrc : FeatureFlag → String
  | .rangeCheck0 => ".rangeCheck0"  | .rangeCheck1 => ".rangeCheck1"
  | .foreignFieldAdd => ".foreignFieldAdd"
  | .foreignFieldMul => ".foreignFieldMul"
  | .xor => ".xor"                  | .rot => ".rot"
  | .lookupTables => ".lookupTables"
  | .runtimeLookupTables => ".runtimeLookupTables"
  | .lookupPattern p => s!"(.lookupPattern {lpSrc p})"
  | .tableWidth n => s!"(.tableWidth {n})"
  | .lookupsPerRow n => s!"(.lookupsPerRow {n})"

/-- One token as a Lean term. -/
def tokenSrc : PolishToken → String
  | .constant c => s!".constant {constSrc c}"
  | .challenge c => s!".challenge {chalSrc c}"
  | .cell col row => s!".cell {colSrc col} {rowSrc row}"
  | .dup => ".dup"
  | .pow n => s!".pow {n}"
  | .add => ".add"
  | .mul => ".mul"
  | .sub => ".sub"
  | .vanishesOnZeroKnowledgeAndPreviousRows => ".vanishesOnZeroKnowledgeAndPreviousRows"
  | .unnormalizedLagrangeBasis zk off =>
      s!".unnormalizedLagrangeBasis {zk} {intLit off}"
  | .store => ".store"
  | .load i => s!".load {i}"
  | .skipIf f n => s!".skipIf {flagSrc f} {n}"
  | .skipIfNot f n => s!".skipIfNot {flagSrc f} {n}"

/-! ## The module -/

/-- A whole generated module: `Pickles.Linearization.<name>` exporting `<defName>`.
One token per line, so the artifact diffs readably and stays inside the column limit. -/
def moduleSrc (defName field : String) (toks : Array PolishToken) : String :=
  let body := toks.toList.map (fun t => "  " ++ tokenSrc t)
  let rows := String.intercalate ",\n" body
  s!"import Pickles.Linearization.Types\n\
     \n\
     /-!\n\
     # The deployed linearization over {field}\n\
     \n\
     GENERATED by `pickles-codegen`'s `gen-tokens` from the Rust dump — do not edit. Its\n\
     PureScript counterparts (`Pickles.Linearization.Pallas`/`Vesta`) come from the same\n\
     JSON, so the two are independent transcriptions of one origin.\n\
     -/\n\
     \n\
     namespace Pickles.Linearization\n\
     \n\
     /-- kimchi's compiled linearization over {field}: {toks.size} tokens. -/\n\
     def {defName} : Array PolishToken := #[\n\
     {rows}]\n\
     \n\
     end Pickles.Linearization\n"

end Pickles.Fixture
