-- | Byte-equality test for `Data.Schnorr.Derive.deriveNonce` against
-- | Mina's `Schnorr.Chunked.Message.derive`. Fixtures are generated by
-- | `mina/.../dump_schnorr_derive_fixtures.exe` (8 Mainnet + 8 Testnet
-- | with message lengths 1..4).
module Test.Data.Schnorr.Derive
  ( spec
  ) where

import Prelude

import Data.Array as Array
import Data.Either (Either(..))
import Data.Schnorr.ChainId (ChainId(..), networkId)
import Data.Schnorr.Derive (deriveNonce)
import Data.Traversable (for_)
import Effect.Aff (Aff)
import Effect.Class (liftEffect)
import Effect.Exception (throw)
import Node.Encoding (Encoding(..))
import Node.FS.Sync as FS
import RandomOracle.Input as Input
import Simple.JSON (readJSON)
import Snarky.Curves.Class (fromHexLe, toBigInt)
import Snarky.Curves.Pallas as Pallas
import Test.Spec (Spec, describe, it)
import Test.Spec.Assertions (shouldEqual)

type FixtureEntry =
  { chain :: String
  , private_key :: String
  , public_key_x :: String
  , public_key_y :: String
  , message :: Array String
  , expected_nonce :: String
  }

type FixtureFile = { fixtures :: Array FixtureEntry }

fixturePath :: String
fixturePath =
  "packages/schnorr/test/fixtures/schnorr_derive/derive_fixtures.json"

parseChain :: String -> Aff ChainId
parseChain = case _ of
  "Mainnet" -> pure Mainnet
  "Testnet" -> pure Testnet
  other -> liftEffect $ throw $ "unknown chain tag: " <> other

spec :: Spec Unit
spec = describe "Data.Schnorr.Derive" do
  it "deriveNonce matches Mina Schnorr.Chunked.Message.derive byte-for-byte" do
    jsonText <- liftEffect $ FS.readTextFile UTF8 fixturePath
    file :: FixtureFile <- case readJSON jsonText of
      Right f -> pure f
      Left e -> liftEffect $ throw $ "parse derive_fixtures.json: " <> show e
    -- Smoke check: dumper writes 16 entries (8 per chain).
    Array.length file.fixtures `shouldEqual` 16
    for_ file.fixtures \entry -> do
      chain <- parseChain entry.chain
      let
        sk :: Pallas.ScalarField
        sk = fromHexLe entry.private_key
        pkx = fromHexLe entry.public_key_x :: Pallas.BaseField
        pky = fromHexLe entry.public_key_y :: Pallas.BaseField

        message :: Array Pallas.BaseField
        message = map fromHexLe entry.message

        expected :: Pallas.ScalarField
        expected = fromHexLe entry.expected_nonce
        got = deriveNonce
          { networkId: networkId chain
          , privateKey: sk
          , publicKey: { x: pkx, y: pky }
          , message: Input.fieldElements message
          }
      -- Compare via BigInt for human-readable failure output on mismatch.
      toBigInt got `shouldEqual` toBigInt expected
