-- | Cross-implementation parity for the out-of-circuit verifier:
-- | `Data.Schnorr.verify` must accept signatures produced by Mina's
-- | `Signature_lib.Schnorr.Chunked.sign`. Fixtures are generated by
-- | `mina/.../dump_schnorr_signatures.exe` (Mainnet + Testnet, message
-- | lengths 1..4) — raw `(pk, message, r, s)` tuples, no kimchi proof.
module Test.Data.Schnorr.VerifyFixtures
  ( spec
  ) where

import Prelude

import Data.Array (head)
import Data.Either (Either(..))
import Data.Maybe (Maybe(..))
import Data.Schnorr (Signature(..), verify)
import Data.Traversable (for_)
import Effect.Aff (Aff)
import Effect.Class (liftEffect)
import Effect.Exception (throw)
import Mina.ChainId (ChainId(..), signaturePrefix)
import Node.Encoding (Encoding(..))
import Node.FS.Sync as FS
import Simple.JSON (readJSON)
import Snarky.Curves.Class (fromHexLe)
import Snarky.Curves.Pallas as Pallas
import Test.Spec (Spec, describe, it)
import Test.Spec.Assertions (shouldEqual)

type Entry =
  { chain :: String
  , public_key_x :: String
  , public_key_y :: String
  , message :: Array String
  , r :: String
  , s :: String
  }

type FixtureFile = { signatures :: Array Entry }

fixturePath :: String
fixturePath =
  "packages/schnorr/test/fixtures/schnorr_signatures/signatures.json"

parseChain :: String -> Aff ChainId
parseChain = case _ of
  "Mainnet" -> pure Mainnet
  "Testnet" -> pure Testnet
  other -> liftEffect $ throw $ "unknown chain tag: " <> other

spec :: Spec Unit
spec = describe "Data.Schnorr.verify (Mina signature fixtures)" do
  it "accepts Mina-produced signatures (Mainnet + Testnet, msg len 1-4) and rejects a tampered one" do
    jsonText <- liftEffect $ FS.readTextFile UTF8 fixturePath
    file :: FixtureFile <- case readJSON jsonText of
      Right f -> pure f
      Left e -> liftEffect $ throw $ "parse signatures.json: " <> show e

    -- Positive: every Mina signature verifies under the PS pure verifier.
    for_ file.signatures \e -> do
      chain <- parseChain e.chain
      let
        sig = Signature { r: fromHexLe e.r, s: fromHexLe e.s }
        pk = { x: fromHexLe e.public_key_x, y: fromHexLe e.public_key_y }
        msg = map fromHexLe e.message :: Array Pallas.BaseField
      verify (signaturePrefix chain) sig pk msg `shouldEqual` true

    -- Negative: flipping `r` must break verification (guards against a
    -- verifier that trivially accepts).
    case head file.signatures of
      Nothing -> liftEffect $ throw "no signature fixtures"
      Just e -> do
        chain <- parseChain e.chain
        let
          sig = Signature { r: fromHexLe e.r + one, s: fromHexLe e.s }
          pk = { x: fromHexLe e.public_key_x, y: fromHexLe e.public_key_y }
          msg = map fromHexLe e.message :: Array Pallas.BaseField
        verify (signaturePrefix chain) sig pk msg `shouldEqual` false
