-- | Hardcoded Tree_proof_return base-case dummy proof plonk values.
-- |
-- | Generated by `dump_tree_proof_return.exe` (trace lines
-- | `tree_dummy.plonk.{alpha.raw,beta,gamma,zeta.raw}`).
-- |
-- | DO NOT EDIT BY HAND. Regenerate with:
-- |   nix develop mina#default -c bash -c \
-- |     'cd mina && KIMCHI_DETERMINISTIC_SEED=42 \
-- |        PICKLES_TRACE_FILE=/tmp/tree_oc_dummy.trace \
-- |        dune exec ./src/lib/crypto/pickles/dump_tree_proof_return/dump_tree_proof_return.exe'
-- | then grep `tree_dummy.plonk` from `/tmp/tree_oc_dummy.trace`.
-- |
-- | Why this exists: OCaml's `Pickles.Proof.dummy Nat.N2.n Nat.N2.n
-- | ~domain_log2:15` (called in Tree_proof_return at runtime after the
-- | NRR+Tree compiles) draws its `statement.plonk.{alpha,beta,gamma,
-- | zeta}` from OCaml's mutable `Ro` module. The Ro counter state at
-- | Tree runtime differs from both `Dummy.*` module-init and SimpleChain
-- | post-compile states, so `simpleChainDummyPlonk` does NOT match.
-- | The values here correspond to the post-Tree-compile state that
-- | Tree_proof_return's `Proof.dummy` actually observes.
-- |
-- | Prev_evals are NOT included: those come from the module-level lazy
-- | `Dummy.evals` which is captured once at module init and shared by
-- | both SimpleChain and Tree Proof.dummy calls. `simpleChainDummyPrevEvals`
-- | already holds those values and can be reused for Tree's slot-1
-- | advice.
module Pickles.Dummy.Tree
  ( TreeDummyPlonk
  , treeDummyPlonk
  ) where

import Prelude

import Data.Array as Array
import Pickles.Util.Fatal (fromJust')
import Data.Vector as Vector
import JS.BigInt (BigInt)
import JS.BigInt as BigInt
import Pickles.Types (StepField)
import Snarky.Circuit.DSL (SizedF, fromBits)

fpChal128 :: String -> SizedF 128 StepField
fpChal128 s =
  let
    bi :: BigInt
    bi = fromJust' ("fpChal128 literal parse: " <> s) (BigInt.fromString s)

    bits :: Array Boolean
    bits = map
      ( \i ->
          BigInt.and (BigInt.shr bi (BigInt.fromInt i)) (BigInt.fromInt 1)
            == BigInt.fromInt 1
      )
      (Array.range 0 127)
  in
    fromBits (fromJust' "tree dummy 128-bit chal: Array.range 0 127 produced 128 bits" (Vector.toVector @128 bits))

type TreeDummyPlonk =
  { alpha :: SizedF 128 StepField
  , beta :: SizedF 128 StepField
  , gamma :: SizedF 128 StepField
  , zeta :: SizedF 128 StepField
  }

treeDummyPlonk :: TreeDummyPlonk
treeDummyPlonk =
  { alpha: fpChal128 "31714329958175783727477075551945886853"
  , beta: fpChal128 "205913416174691502893106945792091291792"
  , gamma: fpChal128 "336749301731200029198653052774605635264"
  , zeta: fpChal128 "158734529890406899856543714254821979093"
  }
