module Pickles.CircuitDiffs.PureScript.StepMainTwoPhaseChainMakeZero
  ( compileStepMainTwoPhaseChainMakeZero
  , StepMainTwoPhaseChainMakeZeroParams
  ) where

-- | step_main circuit for the `make_zero` branch of `two_phase_chain`.
-- |
-- | Configuration: N=0 in a multi-branch compile with mpv=N1, public_input=StepField,
-- | prevs=[], step_domain=2^9. The rule body asserts `self_v = 0` (single R1CS).
-- |
-- | Despite N=0, the wrap CS's `max_proofs_verified=N1` forces the
-- | step PI to pack 34 entries (matching the wrap layout). `mpvMax=1`,
-- | `mpvPad=1` — front-pads one dummy unfinalized_proof slot via the
-- | `dummyUnfp` thunk (which runs since mpvPad>0).
-- |
-- | OCaml reference: `dump_two_phase_chain.ml:95-106` (the `make_zero`
-- | rule). OCaml fixture: `step_main_two_phase_chain_make_zero_circuit.json`
-- | (479 gates, PI=34) generated by the multi-branch
-- | `Pickles.compile_promise` with `~max_proofs_verified:N1`.

import Prelude

import Data.Maybe (Maybe(..))
import Data.Vector (Vector)
import Data.Vector as Vector
import Effect (Effect)
import Effect.Ref as Ref
import Pickles.CircuitDiffs.PureScript.Common (StepArtifact, dummyWrapSg, mkStepArtifact)
import Pickles.Field (StepField)
import Pickles.PublicInputCommit (LagrangeBaseLookup)
import Pickles.Step.Advice (StepAdvice)
import Pickles.Step.Main (RuleOutput, stepMain)
import Snarky.Backend.Advice (noAdvice)
import Snarky.Backend.Compile (compile)
import Snarky.Circuit.DSL (AsProver, F, FVar, Snarky, assertEqual_, const_)
import Snarky.Constraint.Kimchi (KimchiConstraint)
import Snarky.Curves.Class (class PrimeField)
import Snarky.Data.EllipticCurve (AffinePoint)
import Type.Proxy (Proxy(..))
import Unsafe.Coerce (unsafeCoerce)

type StepMainTwoPhaseChainMakeZeroParams =
  { lagrangeAt :: LagrangeBaseLookup 1 StepField
  , blindingH :: AffinePoint (F StepField)
  }

-- | `make_zero` rule: asserts `self_v = 0`. No prevs.
makeZeroRule
  :: forall r
   . PrimeField StepField
  => AsProver StepField r Unit
  -> FVar StepField
  -> Snarky StepField (KimchiConstraint StepField) r
       (RuleOutput 0 Unit Unit)
makeZeroRule _ appState = do
  assertEqual_ appState (const_ zero)
  pure
    { prevPublicInputs: Vector.nil
    , proofMustVerify: Vector.nil
    , publicOutput: unit
    }

compileStepMainTwoPhaseChainMakeZero
  :: StepMainTwoPhaseChainMakeZeroParams -> Effect StepArtifact
compileStepMainTwoPhaseChainMakeZero params = do
  throwawayCaptureRef <- Ref.new Nothing
  -- `carrier` (value-side per-proof witness carrier) is not determined
  -- by `stepMain`'s var-side `StepSlotsCarrier` constraint; pin it here
  -- (mpv=0 ⇒ empty `Unit` carrier).
  let
    dummyAdvice :: StepAdvice _ _ _ _ _ _ Unit _ _
    dummyAdvice = unsafeCoerce unit
  -- mpvMax=1, mpvPad=1: rule has n=0 prevs but the wrap is mpv=N1,
  -- so step PI front-pads 1 dummy unfinalized_proof slot. Output
  -- size = 1*32 + 1 + 1 = 34. `stepMain` derives the front-padding
  -- dummy from `len`.
  mkStepArtifact <$> do
    compile noAdvice (Proxy @Unit) (Proxy @(Vector 34 (F StepField))) (Proxy @(KimchiConstraint StepField))
      ( \_ -> stepMain
          @Unit
          @(F StepField)
          @Unit
          @Unit
          @Unit
          @1
          @1
          @Unit
          @1
          makeZeroRule
          { perSlotLagrangeAt: Vector.nil
          , blindingH: params.blindingH
          , perSlotFopDomainLog2s: Vector.nil
          , perSlotVkBlueprints: unit
          }
          dummyWrapSg
          unit
          dummyAdvice
          throwawayCaptureRef
      )
