module Pickles.CircuitDiffs.PureScript.StepMainTwoPhaseChainIncrement
  ( compileStepMainTwoPhaseChainIncrement
  , StepMainTwoPhaseChainIncrementParams
  , class TwoPhaseChainIncrementAdvice
  , getTwoPhaseChainIncrementPrev
  ) where

-- | step_main circuit for the `increment` branch of `two_phase_chain`.
-- |
-- | Configuration: mpv=N1, public_input=StepField, prevs=[self], step_domain=2^14.
-- | The rule body asserts `self_v = prev + 1` and unconditionally
-- | requires the prev proof to verify (`proof_must_verify = Boolean.true_`).
-- |
-- | Differs from `StepMainSimpleChain` (also N=1, also Input mode) in:
-- |   * Rule body uses `assertEqual_ (one + prev) self_v` directly
-- |     (single R1CS) rather than `equals_ + assertAny_` with a base-case
-- |     branch.
-- |   * `proofMustVerify = true_` (constant) — base case is not allowed.
-- |
-- | OCaml reference: `dump_two_phase_chain.ml:107-131` (the `increment`
-- | rule). OCaml fixture: `step_main_two_phase_chain_increment_circuit.json`
-- | (10795 gates, PI=34) generated by the multi-branch
-- | `Pickles.compile_promise` with `~max_proofs_verified:N1`.

import Prelude

import Control.Monad.Trans.Class (lift)
import Data.Tuple.Nested (Tuple1, tuple1, (/\))
import Data.Vector (Vector, (:<))
import Data.Vector as Vector
import Effect (Effect)
import Effect.Exception (throw)
import Pickles.CircuitDiffs.PureScript.Common (StepArtifact, dummyWrapSg, mkStepArtifact, preComputeSelfStepDomainLog2)
import Pickles.Field (StepField)
import Pickles.PublicInputCommit (LagrangeBaseLookup)
import Pickles.Slots (Compiled, Slot)
import Pickles.Step.Main (RuleOutput, SlotVkBlueprintCompiled(..), stepMain)
import Pickles.Types (StatementIO)
import Snarky.Backend.Compile (compile)
import Snarky.Circuit.CVar (add_) as CVar
import Snarky.Circuit.DSL (class CircuitM, F, FVar, Snarky, assertEqual_, const_, exists, true_)
import Snarky.Constraint.Kimchi (KimchiConstraint)
import Snarky.Constraint.Kimchi as Kimchi
import Snarky.Data.EllipticCurve (AffinePoint)
import Type.Proxy (Proxy(..))

type StepMainTwoPhaseChainIncrementParams =
  { lagrangeAt :: LagrangeBaseLookup StepField
  , blindingH :: AffinePoint (F StepField)
  }

class Monad m <= TwoPhaseChainIncrementAdvice m where
  getTwoPhaseChainIncrementPrev :: Unit -> m (F StepField)

instance TwoPhaseChainIncrementAdvice Effect where
  getTwoPhaseChainIncrementPrev _ =
    throw "TwoPhaseChainIncrementAdvice.getTwoPhaseChainIncrementPrev: not available during compilation"

-- | `increment` rule: asserts `self_v = prev + 1`. No base case branch
-- | (unlike SimpleChain), so `proofMustVerify` is a constant `true_`.
incrementRule
  :: forall t m
   . CircuitM StepField (KimchiConstraint StepField) t m
  => TwoPhaseChainIncrementAdvice m
  => FVar StepField
  -> Snarky (KimchiConstraint StepField) t m
       (RuleOutput 1 (FVar StepField) Unit)
incrementRule appState = do
  prev <- exists $ lift $ getTwoPhaseChainIncrementPrev unit
  assertEqual_ (CVar.add_ (const_ one) prev) appState
  pure
    { prevPublicInputs: prev :< Vector.nil
    , proofMustVerify: true_ :< Vector.nil
    , publicOutput: unit
    }

compileStepMainTwoPhaseChainIncrement
  :: StepArtifact
  -- ^ Make_zero's compiled step artifact. Slot 0's `perSlotFopDomainLog2s`
  -- is `Vector 2 [makeZero, increment]` — make_zero's step domain
  -- log2 is read from this artifact, increment's own is shape-passed.
  -> StepMainTwoPhaseChainIncrementParams
  -> Effect StepArtifact
compileStepMainTwoPhaseChainIncrement makeZeroArt params = do
  -- Slot 0's source = self (the 2-branch proof system). nd=2 dispatch
  -- list: make_zero's step domain (from artifact) + increment's own
  -- step domain (shape-passed).
  let makeZeroLog2 = makeZeroArt.stepDomainLog2
  selfLog2 <- preComputeSelfStepDomainLog2 (runStepCompile makeZeroLog2 1)
  mkStepArtifact <$> runStepCompile makeZeroLog2 selfLog2
  where
  runStepCompile makeZeroLog2 selfLog2 =
    compile (Proxy @Unit) (Proxy @(Vector 34 (F StepField))) (Proxy @(KimchiConstraint StepField))
      -- mpvMax=1 (matches the multi-branch wrap's max_proofs_verified=N1).
      -- mpvPad=0 (this rule's own n = 1 = mpvMax).
      ( \_ -> stepMain
          @(Tuple1 (Slot Compiled 1 1 (StatementIO (F StepField) Unit)))
          @(F StepField)
          @Unit
          @(F StepField)
          @(Tuple1 (StatementIO (F StepField) Unit))
          @1
          @2
          @Unit
          @1
          incrementRule
          { perSlotLagrangeAt: params.lagrangeAt :< Vector.nil
          , blindingH: params.blindingH
          -- nd=2 dispatch list: OCaml's `domain_for_compiled`
          -- (step_verifier.ml:879-899) passes both branches' step
          -- domains to `Pseudo.Domain.to_domain` for runtime dispatch
          -- on the prev's branch index.
          , perSlotFopDomainLog2s:
              (makeZeroLog2 :< selfLog2 :< Vector.nil) :< Vector.nil
          , perSlotVkBlueprints: VkBlueprintShared /\ unit
          }
          dummyWrapSg
          (tuple1 unit)
      )
      Kimchi.initialState
