module Pickles.CircuitDiffs.PureScript.StepMainTwoPhaseChainIncrement
  ( compileStepMainTwoPhaseChainIncrement
  , compileStepMainTwoPhaseChainIncrementWithConstants
  , StepMainTwoPhaseChainIncrementParams
  ) where

-- | step_main circuit for the `increment` branch of `two_phase_chain`.
-- |
-- | Configuration: mpv=N1, public_input=StepField, prevs=[self], step_domain=2^14.
-- | The rule body asserts `self_v = prev + 1` and unconditionally
-- | requires the prev proof to verify (`proof_must_verify = Boolean.true_`).
-- |
-- | Differs from `StepMainSimpleChain` (also N=1, also Input mode) in:
-- |   * Rule body uses `assertEqual_ (one + prev) self_v` directly
-- |     (single R1CS) rather than `equals_ + assertAny_` with a base-case
-- |     branch.
-- |   * `proofMustVerify = true_` (constant) — base case is not allowed.
-- |
-- | OCaml reference: `dump_two_phase_chain.ml:107-131` (the `increment`
-- | rule). OCaml fixture: `step_main_two_phase_chain_increment_circuit.json`
-- | (10795 gates, PI=34) generated by the multi-branch
-- | `Pickles.compile_promise` with `~max_proofs_verified:N1`.

import Prelude

import Data.Array.NonEmpty as NEA
import Data.Maybe (Maybe(..))
import Data.Tuple.Nested (Tuple1, (/\))
import Data.Vector (Vector, (:<))
import Data.Vector as Vector
import Effect (Effect)
import Effect.Ref as Ref
import Pickles.CircuitDiffs.PureScript.Common (StepArtifact, dummyWrapSg, mkStepArtifact, preComputeSelfStepDomainLog2)
import Pickles.CircuitDiffs.Types (Constants)
import Pickles.Dump.Constants (DerivedKey, stepMainConstants)
import Pickles.Field (StepField, WrapField)
import Pickles.Prove.RuleDump (RuleDump, recordRule)
import Pickles.PublicInputCommit (LagrangeBaseLookup)
import Pickles.Slots (Slot)
import Pickles.Step.Main (RuleOutput, SlotVkBlueprint(..), StepMainSrsData, stepMain)
import Pickles.Step.Slots (PrevStatement(..), PrevValues, prevValues, slotWidthInt, slotWidthsOf, toPrevs)
import Pickles.Types (StatementIO(..))
import Snarky.Backend.Advice (noAdvice)
import Snarky.Backend.Compile (compile)
import Snarky.Backend.Kimchi.Types (CRS)
import Snarky.Circuit.CVar (add_) as CVar
import Snarky.Circuit.DSL (AsProver, F, FVar, Snarky, assertEqual_, const_, exists, true_)
import Snarky.Constraint.Kimchi (KimchiConstraint)
import Snarky.Curves.Class (class PrimeField)
import Snarky.Curves.Pasta (PallasG)
import Snarky.Data.EllipticCurve (AffinePoint)
import Type.Proxy (Proxy(..))
import Unsafe.Coerce (unsafeCoerce)

type StepMainTwoPhaseChainIncrementParams =
  { lagrangeAt :: LagrangeBaseLookup 1 StepField
  , blindingH :: AffinePoint (F StepField)
  }

-- | The rule's one self prev slot, at width 1.
type IncrementPrevsSpec = Tuple1 (Slot 1 (StatementIO (F StepField) Unit))

-- | `increment` rule: asserts `self_v = prev + 1`. No base case branch
-- | (unlike SimpleChain), so `proofMustVerify` is a constant `true_`.
incrementRule
  :: forall r
   . PrimeField StepField
  => AsProver StepField r (PrevValues IncrementPrevsSpec)
  -> FVar StepField
  -> Snarky StepField (KimchiConstraint StepField) r
       (RuleOutput IncrementPrevsSpec Unit)
incrementRule getPrevStates appState = do
  prev <- exists $ getPrevStates <#> prevValues <#> \(StatementIO p1 /\ _) -> p1.input
  assertEqual_ (CVar.add_ (const_ one) prev) appState
  pure
    { prevs: toPrevs $
        PrevStatement { publicInput: StatementIO { input: prev, output: unit }, proofMustVerify: true_ }
          /\ unit
    , publicOutput: unit
    }

-- | The tag's width: the multi-branch wrap is mpv=N1.
type Mpv = 1

compileStepMainTwoPhaseChainIncrement
  :: CRS PallasG
  -> StepArtifact
  -- ^ Make_zero's compiled step artifact. Slot 0's `perSlotFopDomainLog2s`
  -- entry is `[makeZero, increment]` — make_zero's step domain
  -- log2 is read from this artifact, increment's own is shape-passed.
  -> StepMainTwoPhaseChainIncrementParams
  -> Effect StepArtifact
compileStepMainTwoPhaseChainIncrement pallasSrs makeZeroArt params =
  _.art <$> compileStepMainTwoPhaseChainIncrementWithConstants pallasSrs makeZeroArt params

-- | `compileStepMainTwoPhaseChainIncrement`, with the constants the circuit
-- | bakes in (`stepMainConstants`) and its rule (`recordRule`), for the
-- | Lean `check_cs` harness.
compileStepMainTwoPhaseChainIncrementWithConstants
  :: CRS PallasG
  -> StepArtifact
  -> StepMainTwoPhaseChainIncrementParams
  -> Effect
       { art :: StepArtifact
       , constants :: DerivedKey PallasG WrapField -> Effect Constants
       , rule :: RuleDump
       }
compileStepMainTwoPhaseChainIncrementWithConstants pallasSrs makeZeroArt params = do
  -- Slot 0's source = self (the 2-branch proof system). Its candidate
  -- list: make_zero's step domain (from artifact) + increment's own
  -- step domain (shape-passed).
  let makeZeroLog2 = makeZeroArt.stepDomainLog2
  selfLog2 <- preComputeSelfStepDomainLog2 (runStepCompile (srsData makeZeroLog2 1))
  art <- mkStepArtifact <$> runStepCompile (srsData makeZeroLog2 selfLog2)
  rule <- recordRule @1 @() @(F StepField) @Unit incrementRule
  pure
    { art
    , rule
    , constants: \selfWrapKey -> do
        stepMainConstants
          (map slotWidthInt (slotWidthsOf (Proxy @IncrementPrevsSpec)))
          (srsData makeZeroLog2 selfLog2)
          pallasSrs
          (Just selfWrapKey :< Vector.nil)
    }
  where
  srsData :: Int -> Int -> StepMainSrsData 1
  srsData makeZeroLog2 selfLog2 =
    { blindingH: params.blindingH
    -- Two candidates: OCaml's `domain_for_compiled`
    -- (step_verifier.ml:879-899) passes both branches' step
    -- domains to `Pseudo.Domain.to_domain` for runtime dispatch
    -- on the prev's branch index.
    , perSlotFopDomainLog2s:
        (NEA.cons' makeZeroLog2 [ selfLog2 ]) :< Vector.nil
    , perSlotNumChunks: 1 :< Vector.nil
    , perSlotVkBlueprints: BlueprintSelf params.lagrangeAt :< Vector.nil
    }

  runStepCompile srsData' = do
    throwawayCaptureRef <- Ref.new Nothing
    let
      dummyAdvice = unsafeCoerce unit
    compile noAdvice (Proxy @Unit) (Proxy @(Vector 34 (F StepField))) (Proxy @(KimchiConstraint StepField))
      -- mpvMax=1 (matches the multi-branch wrap's max_proofs_verified=N1).
      -- mpvPad=0 (this rule's own n = 1 = mpvMax).
      ( \_ -> stepMain
          @IncrementPrevsSpec
          @(F StepField)
          @Unit
          @(Tuple1 (StatementIO (F StepField) Unit))
          @Mpv
          incrementRule
          srsData'
          dummyWrapSg
          dummyAdvice
          throwawayCaptureRef
          Nothing
      )
