-- | N2 wrapper for the wrap_main library circuit.
-- |
-- | Configuration: branches=1, step_widths=[2], Max_widths_by_slot=[N2;N2],
-- | Features.none. The OCaml fixture is generated by
-- | `mina/src/lib/crypto/pickles/dump_simple_chain_n2/dump_simple_chain_n2.ml`,
-- | which calls `Pickles.compile_promise` with a SINGLE rule
-- | (`identifier = "main"`, `prevs = [self; self]`). Therefore
-- | `branches = 1`, not 2 as in the deleted `dump_circuit_impl.ml`
-- | helper this file used to mirror.
-- |
-- | The `stepKeys` VK constants are derived deterministically by
-- | compiling the same Simple_chain N2 step CS that
-- | `step_main_simple_chain_n2_circuit` already byte-matches and then
-- | running the kimchi commitment pipeline (same SRS, same algorithm
-- | OCaml uses). This produces the SAME baked-in VK constants
-- | `Pickles.compile_promise` produces in OC's wrap CS — without
-- | importing anything from the OCaml side.
module Pickles.CircuitDiffs.PureScript.WrapMainN2
  ( compileWrapMainN2
  ) where

import Prelude

import Data.Fin (unsafeFinite)
import Data.Maybe (Maybe(..))
import Data.Vector ((:<))
import Data.Vector as Vector
import Effect (Effect)
import Pickles.CircuitDiffs.PureScript.Common (CompiledCircuit, deriveStepVKFromCompiled)
import Pickles.CircuitDiffs.PureScript.IvpWrap (IvpWrapParams)
import Pickles.CircuitDiffs.PureScript.StepMainSimpleChainN2 (StepMainSimpleChainN2Params, compileStepMainSimpleChainN2)
import Pickles.Types (StepField, WrapField)
import Pickles.Wrap.Main (WrapMainConfig, WrapMainInput, wrapMain)
import Pickles.Wrap.Slots (Slots2)
import Snarky.Backend.Compile (compile)
import Snarky.Backend.Kimchi.Class (createCRS)
import Snarky.Constraint.Kimchi (KimchiConstraint)
import Snarky.Constraint.Kimchi as Kimchi
import Type.Proxy (Proxy(..))

compileWrapMainN2
  :: IvpWrapParams
  -> StepMainSimpleChainN2Params
  -> Effect (CompiledCircuit WrapField)
compileWrapMainN2 { lagrangeAt, blindingH } stepParams = do
  -- Recompile the step CS and derive its VK commitments. This is
  -- exactly what OCaml `compile_promise` does when it produces the
  -- step VK input to `Wrap_main.wrap_main`. Same step CS shape (we
  -- already match `step_main_simple_chain_n2_circuit` byte-for-byte)
  -- + same Vesta SRS + same kimchi commitment algorithm = same VK
  -- constants.
  stepBuiltState <- compileStepMainSimpleChainN2 stepParams
  vestaSrs <- createCRS @StepField
  let
    realStepVK =
      deriveStepVKFromCompiled @2 vestaSrs stepBuiltState
    config :: WrapMainConfig 1
    config =
      { stepWidths: 2 :< Vector.nil
      , domainLog2s: 15 :< Vector.nil
      , stepKeys: realStepVK :< Vector.nil
      , lagrangeAt
      , perBranchLagrangeAt: Nothing
      , blindingH
      , allPossibleDomainLog2s:
          unsafeFinite @16 13 :< unsafeFinite @16 14 :< unsafeFinite @16 15 :< Vector.nil
      }
  compile (Proxy @WrapMainInput) (Proxy @Unit) (Proxy @(KimchiConstraint WrapField))
    (\stmt -> wrapMain @1 @(Slots2 2 2) config stmt)
    Kimchi.initialState
