-- Library root: a formalization of the kimchi proof system.
-- Re-exports the EC oracle, the generic gate, and the custom-gate identities, plus the
-- VarBaseMul scalar-multiplication soundness (abstract + instantiated at the Pasta curves).
import Kimchi.Curve
import Kimchi.Pasta
import Kimchi.Shifted
import Kimchi.Gate.Generic
import Kimchi.Gate.AddComplete
import Kimchi.Gate.VarBaseMul
import Kimchi.Gate.EndoScalar
import Kimchi.Gate.EndoMul
import Kimchi.Gate.Poseidon
import Kimchi.Circuit.VarBaseMul
import Kimchi.Circuit.EndoScalar
import Kimchi.Circuit.EndoMul
import Kimchi.Commitment.IPA.Soundness
import Kimchi.Commitment.IPA.Chunk
import Kimchi.Commitment.IPA.Soundness.Batch
import Kimchi.Commitment.IPA.Soundness.ChunkedBatch
import Kimchi.Quotient.Generic
import Kimchi.Quotient.EndoScalar
import Kimchi.Quotient.Poseidon
import Kimchi.Quotient.Accumulator
import Kimchi.Quotient.Copy
import Kimchi.Index.Basic
import Kimchi.Index.Satisfies
import Kimchi.Index.Aggregate
import Kimchi.Index.Soundness
import Kimchi.Quotient.Wiring
import Kimchi.Quotient.Permutation
import Kimchi.Quotient.GrandProduct
import Kimchi.Quotient.Soundness
import Kimchi.Fixture.Ipa
import Kimchi.Fixture.PS
import Kimchi.Fixture.Parse
import Kimchi.Fixture.Trace
import Kimchi.Sponge.Poseidon
import Kimchi.Sponge.FqSponge
import Kimchi.Sponge.GroupMap
import Kimchi.Verifier.Ipa
import Kimchi.Verifier.Linearization
import Kimchi.Verifier.Reflection
