// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./crypto-provider.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-android-arm64')
        const bindingPackageVersion = require('snarky-crypto-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./crypto-provider.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-android-arm-eabi')
        const bindingPackageVersion = require('snarky-crypto-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./crypto-provider.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-win32-x64-gnu')
        const bindingPackageVersion = require('snarky-crypto-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./crypto-provider.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-win32-x64-msvc')
        const bindingPackageVersion = require('snarky-crypto-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./crypto-provider.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-win32-ia32-msvc')
        const bindingPackageVersion = require('snarky-crypto-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./crypto-provider.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-win32-arm64-msvc')
        const bindingPackageVersion = require('snarky-crypto-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./crypto-provider.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('snarky-crypto-darwin-universal')
      const bindingPackageVersion = require('snarky-crypto-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./crypto-provider.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-darwin-x64')
        const bindingPackageVersion = require('snarky-crypto-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./crypto-provider.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-darwin-arm64')
        const bindingPackageVersion = require('snarky-crypto-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./crypto-provider.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-freebsd-x64')
        const bindingPackageVersion = require('snarky-crypto-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./crypto-provider.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-freebsd-arm64')
        const bindingPackageVersion = require('snarky-crypto-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./crypto-provider.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-x64-musl')
          const bindingPackageVersion = require('snarky-crypto-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./crypto-provider.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-x64-gnu')
          const bindingPackageVersion = require('snarky-crypto-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./crypto-provider.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-arm64-musl')
          const bindingPackageVersion = require('snarky-crypto-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./crypto-provider.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-arm64-gnu')
          const bindingPackageVersion = require('snarky-crypto-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./crypto-provider.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-arm-musleabihf')
          const bindingPackageVersion = require('snarky-crypto-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./crypto-provider.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-arm-gnueabihf')
          const bindingPackageVersion = require('snarky-crypto-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./crypto-provider.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-loong64-musl')
          const bindingPackageVersion = require('snarky-crypto-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./crypto-provider.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-loong64-gnu')
          const bindingPackageVersion = require('snarky-crypto-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./crypto-provider.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-riscv64-musl')
          const bindingPackageVersion = require('snarky-crypto-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./crypto-provider.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('snarky-crypto-linux-riscv64-gnu')
          const bindingPackageVersion = require('snarky-crypto-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./crypto-provider.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-linux-ppc64-gnu')
        const bindingPackageVersion = require('snarky-crypto-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./crypto-provider.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-linux-s390x-gnu')
        const bindingPackageVersion = require('snarky-crypto-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./crypto-provider.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-openharmony-arm64')
        const bindingPackageVersion = require('snarky-crypto-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./crypto-provider.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-openharmony-x64')
        const bindingPackageVersion = require('snarky-crypto-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./crypto-provider.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('snarky-crypto-openharmony-arm')
        const bindingPackageVersion = require('snarky-crypto-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./crypto-provider.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('snarky-crypto-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.bn254BasefieldAdd = nativeBinding.bn254BasefieldAdd
module.exports.bn254BasefieldDiv = nativeBinding.bn254BasefieldDiv
module.exports.bn254BasefieldEq = nativeBinding.bn254BasefieldEq
module.exports.bn254BasefieldFromBigint = nativeBinding.bn254BasefieldFromBigint
module.exports.bn254BasefieldFromString = nativeBinding.bn254BasefieldFromString
module.exports.bn254BasefieldInvert = nativeBinding.bn254BasefieldInvert
module.exports.bn254BasefieldModulus = nativeBinding.bn254BasefieldModulus
module.exports.bn254BasefieldMul = nativeBinding.bn254BasefieldMul
module.exports.bn254BasefieldOne = nativeBinding.bn254BasefieldOne
module.exports.bn254BasefieldPow = nativeBinding.bn254BasefieldPow
module.exports.bn254BasefieldRand = nativeBinding.bn254BasefieldRand
module.exports.bn254BasefieldSub = nativeBinding.bn254BasefieldSub
module.exports.bn254BasefieldToBigint = nativeBinding.bn254BasefieldToBigint
module.exports.bn254BasefieldToString = nativeBinding.bn254BasefieldToString
module.exports.bn254BasefieldZero = nativeBinding.bn254BasefieldZero
module.exports.bn254CircuitCreate = nativeBinding.bn254CircuitCreate
module.exports.bn254CircuitIsSatisfiedBy = nativeBinding.bn254CircuitIsSatisfiedBy
module.exports.bn254GroupAdd = nativeBinding.bn254GroupAdd
module.exports.bn254GroupEq = nativeBinding.bn254GroupEq
module.exports.bn254GroupFromAffine = nativeBinding.bn254GroupFromAffine
module.exports.bn254GroupGenerator = nativeBinding.bn254GroupGenerator
module.exports.bn254GroupIdentity = nativeBinding.bn254GroupIdentity
module.exports.bn254GroupNeg = nativeBinding.bn254GroupNeg
module.exports.bn254GroupRand = nativeBinding.bn254GroupRand
module.exports.bn254GroupScale = nativeBinding.bn254GroupScale
module.exports.bn254GroupToAffine = nativeBinding.bn254GroupToAffine
module.exports.bn254GroupToString = nativeBinding.bn254GroupToString
module.exports.bn254GroupWeierstrassA = nativeBinding.bn254GroupWeierstrassA
module.exports.bn254GroupWeierstrassB = nativeBinding.bn254GroupWeierstrassB
module.exports.bn254Prove = nativeBinding.bn254Prove
module.exports.bn254ScalarfieldAdd = nativeBinding.bn254ScalarfieldAdd
module.exports.bn254ScalarfieldDiv = nativeBinding.bn254ScalarfieldDiv
module.exports.bn254ScalarfieldEq = nativeBinding.bn254ScalarfieldEq
module.exports.bn254ScalarfieldFromBigint = nativeBinding.bn254ScalarfieldFromBigint
module.exports.bn254ScalarfieldFromString = nativeBinding.bn254ScalarfieldFromString
module.exports.bn254ScalarfieldInvert = nativeBinding.bn254ScalarfieldInvert
module.exports.bn254ScalarfieldModulus = nativeBinding.bn254ScalarfieldModulus
module.exports.bn254ScalarfieldMul = nativeBinding.bn254ScalarfieldMul
module.exports.bn254ScalarfieldOne = nativeBinding.bn254ScalarfieldOne
module.exports.bn254ScalarfieldPow = nativeBinding.bn254ScalarfieldPow
module.exports.bn254ScalarfieldRand = nativeBinding.bn254ScalarfieldRand
module.exports.bn254ScalarfieldSub = nativeBinding.bn254ScalarfieldSub
module.exports.bn254ScalarfieldToBigint = nativeBinding.bn254ScalarfieldToBigint
module.exports.bn254ScalarfieldToString = nativeBinding.bn254ScalarfieldToString
module.exports.bn254ScalarfieldZero = nativeBinding.bn254ScalarfieldZero
module.exports.bn254Setup = nativeBinding.bn254Setup
module.exports.bn254Verify = nativeBinding.bn254Verify
module.exports.bn254WitnessCreate = nativeBinding.bn254WitnessCreate
module.exports.bulletproofsInit = nativeBinding.bulletproofsInit
module.exports.evaluatePallasLinearization = nativeBinding.evaluatePallasLinearization
module.exports.evaluateVestaLinearization = nativeBinding.evaluateVestaLinearization
module.exports.gateWiresGetWire = nativeBinding.gateWiresGetWire
module.exports.gateWiresNewFromWires = nativeBinding.gateWiresNewFromWires
module.exports.getColumnsCount = nativeBinding.getColumnsCount
module.exports.pallasBw19Params = nativeBinding.pallasBw19Params
module.exports.pallasChallengePolyCommitment = nativeBinding.pallasChallengePolyCommitment
module.exports.pallasCircuitCreate = nativeBinding.pallasCircuitCreate
module.exports.pallasCircuitGateCoeffCount = nativeBinding.pallasCircuitGateCoeffCount
module.exports.pallasCircuitGateGetCoeff = nativeBinding.pallasCircuitGateGetCoeff
module.exports.pallasCircuitGateGetWires = nativeBinding.pallasCircuitGateGetWires
module.exports.pallasCircuitGateNew = nativeBinding.pallasCircuitGateNew
module.exports.pallasCircuitIsSatisfiedBy = nativeBinding.pallasCircuitIsSatisfiedBy
module.exports.pallasCircuitN = nativeBinding.pallasCircuitN
module.exports.pallasCircuitQ = nativeBinding.pallasCircuitQ
module.exports.pallasCombinedPolynomialCommitment = nativeBinding.pallasCombinedPolynomialCommitment
module.exports.pallasComputeB0 = nativeBinding.pallasComputeB0
module.exports.pallasComputeUT = nativeBinding.pallasComputeUT
module.exports.pallasConstraintSystemCreate = nativeBinding.pallasConstraintSystemCreate
module.exports.pallasConstraintSystemCreateWithPrevChallenges = nativeBinding.pallasConstraintSystemCreateWithPrevChallenges
module.exports.pallasConstraintSystemToJson = nativeBinding.pallasConstraintSystemToJson
module.exports.pallasCreateProof = nativeBinding.pallasCreateProof
module.exports.pallasCreateProofWithPrev = nativeBinding.pallasCreateProofWithPrev
module.exports.pallasCrsCreate = nativeBinding.pallasCrsCreate
module.exports.pallasCrsLoadFromCache = nativeBinding.pallasCrsLoadFromCache
module.exports.pallasCrsSize = nativeBinding.pallasCrsSize
module.exports.pallasDebugVerify = nativeBinding.pallasDebugVerify
module.exports.pallasDomainGenerator = nativeBinding.pallasDomainGenerator
module.exports.pallasDomainPrefixToField = nativeBinding.pallasDomainPrefixToField
module.exports.pallasDomainShifts = nativeBinding.pallasDomainShifts
module.exports.pallasEndoBase = nativeBinding.pallasEndoBase
module.exports.pallasEndoScalar = nativeBinding.pallasEndoScalar
module.exports.pallasFtComm = nativeBinding.pallasFtComm
module.exports.pallasGatesToJson = nativeBinding.pallasGatesToJson
module.exports.pallasGroupAdd = nativeBinding.pallasGroupAdd
module.exports.pallasGroupEq = nativeBinding.pallasGroupEq
module.exports.pallasGroupFromAffine = nativeBinding.pallasGroupFromAffine
module.exports.pallasGroupGenerator = nativeBinding.pallasGroupGenerator
module.exports.pallasGroupIdentity = nativeBinding.pallasGroupIdentity
module.exports.pallasGroupMap = nativeBinding.pallasGroupMap
module.exports.pallasGroupNeg = nativeBinding.pallasGroupNeg
module.exports.pallasGroupRand = nativeBinding.pallasGroupRand
module.exports.pallasGroupScale = nativeBinding.pallasGroupScale
module.exports.pallasGroupToAffine = nativeBinding.pallasGroupToAffine
module.exports.pallasGroupToString = nativeBinding.pallasGroupToString
module.exports.pallasGroupWeierstrassA = nativeBinding.pallasGroupWeierstrassA
module.exports.pallasGroupWeierstrassB = nativeBinding.pallasGroupWeierstrassB
module.exports.pallasInitWithDomain = nativeBinding.pallasInitWithDomain
module.exports.pallasLagrangeCommitments = nativeBinding.pallasLagrangeCommitments
module.exports.pallasPermScalar = nativeBinding.pallasPermScalar
module.exports.pallasPermutationVanishingPolynomial = nativeBinding.pallasPermutationVanishingPolynomial
module.exports.pallasPoseidonApplyMds = nativeBinding.pallasPoseidonApplyMds
module.exports.pallasPoseidonFullRound = nativeBinding.pallasPoseidonFullRound
module.exports.pallasPoseidonGetMdsMatrix = nativeBinding.pallasPoseidonGetMdsMatrix
module.exports.pallasPoseidonGetNumRounds = nativeBinding.pallasPoseidonGetNumRounds
module.exports.pallasPoseidonGetRoundConstants = nativeBinding.pallasPoseidonGetRoundConstants
module.exports.pallasPoseidonHash = nativeBinding.pallasPoseidonHash
module.exports.pallasPoseidonPermute = nativeBinding.pallasPoseidonPermute
module.exports.pallasPoseidonSbox = nativeBinding.pallasPoseidonSbox
module.exports.pallasProofBulletproofChallenges = nativeBinding.pallasProofBulletproofChallenges
module.exports.pallasProofCoefficientEvals = nativeBinding.pallasProofCoefficientEvals
module.exports.pallasProofCommitments = nativeBinding.pallasProofCommitments
module.exports.pallasProofIndexEvals = nativeBinding.pallasProofIndexEvals
module.exports.pallasProofIpaRounds = nativeBinding.pallasProofIpaRounds
module.exports.pallasProofLrProd = nativeBinding.pallasProofLrProd
module.exports.pallasProofOpeningDelta = nativeBinding.pallasProofOpeningDelta
module.exports.pallasProofOpeningLr = nativeBinding.pallasProofOpeningLr
module.exports.pallasProofOpeningPrechallenges = nativeBinding.pallasProofOpeningPrechallenges
module.exports.pallasProofOpeningSg = nativeBinding.pallasProofOpeningSg
module.exports.pallasProofOpeningZ1 = nativeBinding.pallasProofOpeningZ1
module.exports.pallasProofOpeningZ2 = nativeBinding.pallasProofOpeningZ2
module.exports.pallasProofOracles = nativeBinding.pallasProofOracles
module.exports.pallasProofSigmaEvals = nativeBinding.pallasProofSigmaEvals
module.exports.pallasProofWitnessEvals = nativeBinding.pallasProofWitnessEvals
module.exports.pallasProofZEvals = nativeBinding.pallasProofZEvals
module.exports.pallasProve = nativeBinding.pallasProve
module.exports.pallasProverIndexBlindingGenerator = nativeBinding.pallasProverIndexBlindingGenerator
module.exports.pallasProverIndexCoefficientEvaluations = nativeBinding.pallasProverIndexCoefficientEvaluations
module.exports.pallasProverIndexCreate = nativeBinding.pallasProverIndexCreate
module.exports.pallasProverIndexDomainLog2 = nativeBinding.pallasProverIndexDomainLog2
module.exports.pallasProverIndexSelectorEvaluations = nativeBinding.pallasProverIndexSelectorEvaluations
module.exports.pallasProverIndexShifts = nativeBinding.pallasProverIndexShifts
module.exports.pallasProverIndexVerify = nativeBinding.pallasProverIndexVerify
module.exports.pallasProverIndexWitnessEvaluations = nativeBinding.pallasProverIndexWitnessEvaluations
module.exports.pallasPublicComm = nativeBinding.pallasPublicComm
module.exports.pallasScalarfieldAdd = nativeBinding.pallasScalarfieldAdd
module.exports.pallasScalarfieldDiv = nativeBinding.pallasScalarfieldDiv
module.exports.pallasScalarfieldEq = nativeBinding.pallasScalarfieldEq
module.exports.pallasScalarfieldFromBigint = nativeBinding.pallasScalarfieldFromBigint
module.exports.pallasScalarfieldFromHexLe = nativeBinding.pallasScalarfieldFromHexLe
module.exports.pallasScalarfieldFromString = nativeBinding.pallasScalarfieldFromString
module.exports.pallasScalarfieldInvert = nativeBinding.pallasScalarfieldInvert
module.exports.pallasScalarfieldIsSquare = nativeBinding.pallasScalarfieldIsSquare
module.exports.pallasScalarfieldModulus = nativeBinding.pallasScalarfieldModulus
module.exports.pallasScalarfieldMul = nativeBinding.pallasScalarfieldMul
module.exports.pallasScalarfieldOne = nativeBinding.pallasScalarfieldOne
module.exports.pallasScalarfieldPow = nativeBinding.pallasScalarfieldPow
module.exports.pallasScalarfieldRand = nativeBinding.pallasScalarfieldRand
module.exports.pallasScalarfieldSqrt = nativeBinding.pallasScalarfieldSqrt
module.exports.pallasScalarfieldSub = nativeBinding.pallasScalarfieldSub
module.exports.pallasScalarfieldToBigint = nativeBinding.pallasScalarfieldToBigint
module.exports.pallasScalarfieldToHexLe = nativeBinding.pallasScalarfieldToHexLe
module.exports.pallasScalarfieldToString = nativeBinding.pallasScalarfieldToString
module.exports.pallasScalarfieldZero = nativeBinding.pallasScalarfieldZero
module.exports.pallasSpongeAbsorb = nativeBinding.pallasSpongeAbsorb
module.exports.pallasSpongeCheckpoint = nativeBinding.pallasSpongeCheckpoint
module.exports.pallasSpongeCheckpointMode = nativeBinding.pallasSpongeCheckpointMode
module.exports.pallasSpongeCheckpointModeCount = nativeBinding.pallasSpongeCheckpointModeCount
module.exports.pallasSpongeCheckpointState = nativeBinding.pallasSpongeCheckpointState
module.exports.pallasSpongeCreate = nativeBinding.pallasSpongeCreate
module.exports.pallasSpongeSqueeze = nativeBinding.pallasSpongeSqueeze
module.exports.pallasSrsBlindingGenerator = nativeBinding.pallasSrsBlindingGenerator
module.exports.pallasSrsBPolyCommitment = nativeBinding.pallasSrsBPolyCommitment
module.exports.pallasSrsCreate = nativeBinding.pallasSrsCreate
module.exports.pallasSrsLagrangeCommitmentAt = nativeBinding.pallasSrsLagrangeCommitmentAt
module.exports.pallasSrsLagrangeCommitments = nativeBinding.pallasSrsLagrangeCommitments
module.exports.pallasSrsSize = nativeBinding.pallasSrsSize
module.exports.pallasStatementCreate = nativeBinding.pallasStatementCreate
module.exports.pallasUnnormalizedLagrangeBasis = nativeBinding.pallasUnnormalizedLagrangeBasis
module.exports.pallasVanishesOnZkAndPreviousRows = nativeBinding.pallasVanishesOnZkAndPreviousRows
module.exports.pallasVerifierIndex = nativeBinding.pallasVerifierIndex
module.exports.pallasVerifierIndexColumnComms = nativeBinding.pallasVerifierIndexColumnComms
module.exports.pallasVerifierIndexDigest = nativeBinding.pallasVerifierIndexDigest
module.exports.pallasVerifierIndexMaxPolySize = nativeBinding.pallasVerifierIndexMaxPolySize
module.exports.pallasVerifierIndexSigmaCommLast = nativeBinding.pallasVerifierIndexSigmaCommLast
module.exports.pallasVerify = nativeBinding.pallasVerify
module.exports.pallasVerifyOpeningProof = nativeBinding.pallasVerifyOpeningProof
module.exports.pallasWitnessCreate = nativeBinding.pallasWitnessCreate
module.exports.pallasWitnessSize = nativeBinding.pallasWitnessSize
module.exports.verifyPallasCompleteAdd = nativeBinding.verifyPallasCompleteAdd
module.exports.verifyPallasGeneric = nativeBinding.verifyPallasGeneric
module.exports.verifyPallasPoseidonGadget = nativeBinding.verifyPallasPoseidonGadget
module.exports.verifyPallasVarbasemul = nativeBinding.verifyPallasVarbasemul
module.exports.verifyVestaCompleteAdd = nativeBinding.verifyVestaCompleteAdd
module.exports.verifyVestaGeneric = nativeBinding.verifyVestaGeneric
module.exports.verifyVestaPoseidonGadget = nativeBinding.verifyVestaPoseidonGadget
module.exports.verifyVestaVarbasemul = nativeBinding.verifyVestaVarbasemul
module.exports.vestaBw19Params = nativeBinding.vestaBw19Params
module.exports.vestaChallengePolyCommitment = nativeBinding.vestaChallengePolyCommitment
module.exports.vestaCircuitCreate = nativeBinding.vestaCircuitCreate
module.exports.vestaCircuitGateCoeffCount = nativeBinding.vestaCircuitGateCoeffCount
module.exports.vestaCircuitGateGetCoeff = nativeBinding.vestaCircuitGateGetCoeff
module.exports.vestaCircuitGateGetWires = nativeBinding.vestaCircuitGateGetWires
module.exports.vestaCircuitGateNew = nativeBinding.vestaCircuitGateNew
module.exports.vestaCircuitIsSatisfiedBy = nativeBinding.vestaCircuitIsSatisfiedBy
module.exports.vestaCircuitN = nativeBinding.vestaCircuitN
module.exports.vestaCircuitQ = nativeBinding.vestaCircuitQ
module.exports.vestaCombinedPolynomialCommitment = nativeBinding.vestaCombinedPolynomialCommitment
module.exports.vestaComputeB0 = nativeBinding.vestaComputeB0
module.exports.vestaComputeUT = nativeBinding.vestaComputeUT
module.exports.vestaConstraintSystemCreate = nativeBinding.vestaConstraintSystemCreate
module.exports.vestaConstraintSystemCreateWithPrevChallenges = nativeBinding.vestaConstraintSystemCreateWithPrevChallenges
module.exports.vestaConstraintSystemToJson = nativeBinding.vestaConstraintSystemToJson
module.exports.vestaCreateProof = nativeBinding.vestaCreateProof
module.exports.vestaCreateProofWithPrev = nativeBinding.vestaCreateProofWithPrev
module.exports.vestaCrsCreate = nativeBinding.vestaCrsCreate
module.exports.vestaCrsLoadFromCache = nativeBinding.vestaCrsLoadFromCache
module.exports.vestaCrsSize = nativeBinding.vestaCrsSize
module.exports.vestaDebugVerify = nativeBinding.vestaDebugVerify
module.exports.vestaDomainGenerator = nativeBinding.vestaDomainGenerator
module.exports.vestaDomainPrefixToField = nativeBinding.vestaDomainPrefixToField
module.exports.vestaDomainShifts = nativeBinding.vestaDomainShifts
module.exports.vestaEndoBase = nativeBinding.vestaEndoBase
module.exports.vestaEndoScalar = nativeBinding.vestaEndoScalar
module.exports.vestaFtComm = nativeBinding.vestaFtComm
module.exports.vestaGatesToJson = nativeBinding.vestaGatesToJson
module.exports.vestaGroupAdd = nativeBinding.vestaGroupAdd
module.exports.vestaGroupEq = nativeBinding.vestaGroupEq
module.exports.vestaGroupFromAffine = nativeBinding.vestaGroupFromAffine
module.exports.vestaGroupGenerator = nativeBinding.vestaGroupGenerator
module.exports.vestaGroupIdentity = nativeBinding.vestaGroupIdentity
module.exports.vestaGroupMap = nativeBinding.vestaGroupMap
module.exports.vestaGroupNeg = nativeBinding.vestaGroupNeg
module.exports.vestaGroupRand = nativeBinding.vestaGroupRand
module.exports.vestaGroupScale = nativeBinding.vestaGroupScale
module.exports.vestaGroupToAffine = nativeBinding.vestaGroupToAffine
module.exports.vestaGroupToString = nativeBinding.vestaGroupToString
module.exports.vestaGroupWeierstrassA = nativeBinding.vestaGroupWeierstrassA
module.exports.vestaGroupWeierstrassB = nativeBinding.vestaGroupWeierstrassB
module.exports.vestaInitWithDomain = nativeBinding.vestaInitWithDomain
module.exports.vestaLagrangeCommitments = nativeBinding.vestaLagrangeCommitments
module.exports.vestaMakeWireProof = nativeBinding.vestaMakeWireProof
module.exports.vestaPermScalar = nativeBinding.vestaPermScalar
module.exports.vestaPermutationVanishingPolynomial = nativeBinding.vestaPermutationVanishingPolynomial
module.exports.vestaPoseidonApplyMds = nativeBinding.vestaPoseidonApplyMds
module.exports.vestaPoseidonFullRound = nativeBinding.vestaPoseidonFullRound
module.exports.vestaPoseidonGetMdsMatrix = nativeBinding.vestaPoseidonGetMdsMatrix
module.exports.vestaPoseidonGetNumRounds = nativeBinding.vestaPoseidonGetNumRounds
module.exports.vestaPoseidonGetRoundConstants = nativeBinding.vestaPoseidonGetRoundConstants
module.exports.vestaPoseidonHash = nativeBinding.vestaPoseidonHash
module.exports.vestaPoseidonPermute = nativeBinding.vestaPoseidonPermute
module.exports.vestaPoseidonSbox = nativeBinding.vestaPoseidonSbox
module.exports.vestaProofBulletproofChallenges = nativeBinding.vestaProofBulletproofChallenges
module.exports.vestaProofCoefficientEvals = nativeBinding.vestaProofCoefficientEvals
module.exports.vestaProofCommitments = nativeBinding.vestaProofCommitments
module.exports.vestaProofIndexEvals = nativeBinding.vestaProofIndexEvals
module.exports.vestaProofIpaRounds = nativeBinding.vestaProofIpaRounds
module.exports.vestaProofLrProd = nativeBinding.vestaProofLrProd
module.exports.vestaProofOpeningDelta = nativeBinding.vestaProofOpeningDelta
module.exports.vestaProofOpeningLr = nativeBinding.vestaProofOpeningLr
module.exports.vestaProofOpeningPrechallenges = nativeBinding.vestaProofOpeningPrechallenges
module.exports.vestaProofOpeningSg = nativeBinding.vestaProofOpeningSg
module.exports.vestaProofOpeningZ1 = nativeBinding.vestaProofOpeningZ1
module.exports.vestaProofOpeningZ2 = nativeBinding.vestaProofOpeningZ2
module.exports.vestaProofOracles = nativeBinding.vestaProofOracles
module.exports.vestaProofSigmaEvals = nativeBinding.vestaProofSigmaEvals
module.exports.vestaProofWitnessEvals = nativeBinding.vestaProofWitnessEvals
module.exports.vestaProofZEvals = nativeBinding.vestaProofZEvals
module.exports.vestaProve = nativeBinding.vestaProve
module.exports.vestaProverIndexBlindingGenerator = nativeBinding.vestaProverIndexBlindingGenerator
module.exports.vestaProverIndexCoefficientEvaluations = nativeBinding.vestaProverIndexCoefficientEvaluations
module.exports.vestaProverIndexCreate = nativeBinding.vestaProverIndexCreate
module.exports.vestaProverIndexDomainLog2 = nativeBinding.vestaProverIndexDomainLog2
module.exports.vestaProverIndexSelectorEvaluations = nativeBinding.vestaProverIndexSelectorEvaluations
module.exports.vestaProverIndexShifts = nativeBinding.vestaProverIndexShifts
module.exports.vestaProverIndexVerify = nativeBinding.vestaProverIndexVerify
module.exports.vestaProverIndexWitnessEvaluations = nativeBinding.vestaProverIndexWitnessEvaluations
module.exports.vestaPublicComm = nativeBinding.vestaPublicComm
module.exports.vestaScalarfieldAdd = nativeBinding.vestaScalarfieldAdd
module.exports.vestaScalarfieldDiv = nativeBinding.vestaScalarfieldDiv
module.exports.vestaScalarfieldEq = nativeBinding.vestaScalarfieldEq
module.exports.vestaScalarfieldFromBigint = nativeBinding.vestaScalarfieldFromBigint
module.exports.vestaScalarfieldFromHexLe = nativeBinding.vestaScalarfieldFromHexLe
module.exports.vestaScalarfieldFromString = nativeBinding.vestaScalarfieldFromString
module.exports.vestaScalarfieldInvert = nativeBinding.vestaScalarfieldInvert
module.exports.vestaScalarfieldIsSquare = nativeBinding.vestaScalarfieldIsSquare
module.exports.vestaScalarfieldModulus = nativeBinding.vestaScalarfieldModulus
module.exports.vestaScalarfieldMul = nativeBinding.vestaScalarfieldMul
module.exports.vestaScalarfieldOne = nativeBinding.vestaScalarfieldOne
module.exports.vestaScalarfieldPow = nativeBinding.vestaScalarfieldPow
module.exports.vestaScalarfieldRand = nativeBinding.vestaScalarfieldRand
module.exports.vestaScalarfieldSqrt = nativeBinding.vestaScalarfieldSqrt
module.exports.vestaScalarfieldSub = nativeBinding.vestaScalarfieldSub
module.exports.vestaScalarfieldToBigint = nativeBinding.vestaScalarfieldToBigint
module.exports.vestaScalarfieldToHexLe = nativeBinding.vestaScalarfieldToHexLe
module.exports.vestaScalarfieldToString = nativeBinding.vestaScalarfieldToString
module.exports.vestaScalarfieldZero = nativeBinding.vestaScalarfieldZero
module.exports.vestaSpongeAbsorb = nativeBinding.vestaSpongeAbsorb
module.exports.vestaSpongeCheckpoint = nativeBinding.vestaSpongeCheckpoint
module.exports.vestaSpongeCheckpointMode = nativeBinding.vestaSpongeCheckpointMode
module.exports.vestaSpongeCheckpointModeCount = nativeBinding.vestaSpongeCheckpointModeCount
module.exports.vestaSpongeCheckpointState = nativeBinding.vestaSpongeCheckpointState
module.exports.vestaSpongeCreate = nativeBinding.vestaSpongeCreate
module.exports.vestaSpongeSqueeze = nativeBinding.vestaSpongeSqueeze
module.exports.vestaSrsBlindingGenerator = nativeBinding.vestaSrsBlindingGenerator
module.exports.vestaSrsBPolyCommitment = nativeBinding.vestaSrsBPolyCommitment
module.exports.vestaSrsCreate = nativeBinding.vestaSrsCreate
module.exports.vestaSrsLagrangeCommitmentAt = nativeBinding.vestaSrsLagrangeCommitmentAt
module.exports.vestaSrsLagrangeCommitments = nativeBinding.vestaSrsLagrangeCommitments
module.exports.vestaSrsSize = nativeBinding.vestaSrsSize
module.exports.vestaStatementCreate = nativeBinding.vestaStatementCreate
module.exports.vestaUnnormalizedLagrangeBasis = nativeBinding.vestaUnnormalizedLagrangeBasis
module.exports.vestaVanishesOnZkAndPreviousRows = nativeBinding.vestaVanishesOnZkAndPreviousRows
module.exports.vestaVerifierIndex = nativeBinding.vestaVerifierIndex
module.exports.vestaVerifierIndexColumnComms = nativeBinding.vestaVerifierIndexColumnComms
module.exports.vestaVerifierIndexDigest = nativeBinding.vestaVerifierIndexDigest
module.exports.vestaVerifierIndexMaxPolySize = nativeBinding.vestaVerifierIndexMaxPolySize
module.exports.vestaVerifierIndexSigmaCommLast = nativeBinding.vestaVerifierIndexSigmaCommLast
module.exports.vestaVerify = nativeBinding.vestaVerify
module.exports.vestaVerifyOpeningProof = nativeBinding.vestaVerifyOpeningProof
module.exports.vestaWitnessCreate = nativeBinding.vestaWitnessCreate
module.exports.vestaWitnessSize = nativeBinding.vestaWitnessSize
module.exports.wireGetCol = nativeBinding.wireGetCol
module.exports.wireGetRow = nativeBinding.wireGetRow
module.exports.wireNew = nativeBinding.wireNew
