#!/usr/bin/env python3
"""Extract Mina-Kimchi Poseidon round constants + MDS from upstream Rust.

Reads `mina/.../poseidon/src/pasta/f{p,q}_kimchi.rs` and emits the
`mds: [...], roundConstants: [...]` body block consumed by
`pasta-runtime/PastaPoseidonConstants.js`.

The Rust source files are generated from `params.sage` (see the
`/* Generated by ./params.sage --rounds 55 rust 3 kimchi */` comment at
the top of each `f{p,q}_kimchi.rs`); this script lets us regenerate the
JS constants on demand if upstream re-runs `params.sage`. Format is
intentionally simple — single-quoted decimal strings, two-space
indentation, trailing commas — to match the hand-written Fp block
already in `PastaPoseidonConstants.js`.

Usage:
  python3 tools/extract_poseidon_params.py \\
    mina/src/lib/crypto/proof-systems/poseidon/src/pasta/fq_kimchi.rs \\
    > /tmp/fq_block.txt

Expected output has 174 constants total (9 MDS + 55 rounds × 3
round-constants per round = 9 + 165 = 174).
"""
import re, sys

if len(sys.argv) != 2:
    print("usage: extract_poseidon_params.py <fp_kimchi.rs|fq_kimchi.rs>", file=sys.stderr)
    sys.exit(2)

src = open(sys.argv[1]).read()
# Pull every decimal literal that appears inside Fp::from_str("...").unwrap()
# (or Fq::). DOTALL so the string body can wrap across lines, which the
# rustfmt'd source does.
nums = re.findall(
    r'F[pq]::from_str\(\s*"(\d+)",?\s*\)\s*\.unwrap\(\)',
    src,
    flags=re.DOTALL,
)
expected = 9 + 55 * 3  # mds + round_constants
if len(nums) != expected:
    print(f"ERR: expected {expected} constants, got {len(nums)}", file=sys.stderr)
    sys.exit(1)

mds_flat = nums[:9]
rc_flat = nums[9:]
mds = [mds_flat[i : i + 3] for i in range(0, 9, 3)]
rc = [rc_flat[i : i + 3] for i in range(0, 165, 3)]


def js_triple(triple, indent="    "):
    inner = ",\n".join(indent + "  '" + n + "'" for n in triple)
    return "[\n" + inner + ",\n" + indent + "]"


out = []
out.append("  mds: [")
for t in mds:
    out.append("    " + js_triple(t) + ",")
out.append("  ],")
out.append("  roundConstants: [")
for t in rc:
    out.append("    " + js_triple(t) + ",")
out.append("  ],")
print("\n".join(out))
